### ISSUE TITLE
Getting Error "IndexError: list index out of range"

### ISSUE THREAD

**Issue by modiutpal** [mjsqu/tap-msipranges#1]
We get the error "IndexError: list index out of range".

Investigation suggests that class "'failoverLink'" has been removed from the web page (https://www.microsoft.com/en-us/download/confirmation.aspx?id=56519) on 06-Dec, which causes failure to get value for "download_link_xpath" and eventually failing the download_url.

A suggested fix is to remove "a[contains(@class, 'failoverLink') and " from the "download_link_xpath" config property. 

Also noticed that the web page URL is changed from "https://www.microsoft.com/en-us/download/confirmation.aspx?id=56519" to "https://www.microsoft.com/en-us/download/details.aspx?id=56519".

**Comment by mjsqu** [comment]
Thanks @modiutpal - your change #2 has fixed this
